services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    mem_limit: 4G
    memswap_limit: 4G
    security_opt:
      - no-new-privileges=true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.${MY_DOMAIN}`)'
      - 'traefik.http.routers.jellyfin.entryPoints=https'
      - 'traefik.http.routers.jellyfin.tls=true'
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    environment:
      TZ: Asia/Kolkata
    volumes:
      - type: tmpfs
        target: /cache
      - type: bind
        source: ${CONFIG_LOCATION}/Jellyfin
        target: /config
      - type: bind
        source: ${MOVIES_LOCATION}
        target: /media/Movies
        read_only: true
      - type: bind
        source: ${TV_SHOWS_LOCATION}
        target: /media/TV_Shows
        read_only: true
      - type: bind
        source: ${MUSIC_LOCATION}
        target: /media/Music
        read_only: true
    ports:
      - "8002:8096"
    networks:
          proxy:

networks:
  proxy:
     external: true
