services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    mem_limit: 4G
    memswap_limit: 4G
    dns:
      - 1.1.1.1
      - 9.9.9.9
    security_opt:
      - no-new-privileges=true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.deluge.rule=Host(`deluge.${MY_DOMAIN}`)'
      - 'traefik.http.routers.deluge.entryPoints=https'
      - 'traefik.http.routers.deluge.tls=true'
      - "traefik.http.services.deluge.loadbalancer.server.port=8112"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - type: bind
        source: ${CONFIG_LOCATION}/Deluge
        target: /config
      - type: bind
        source: ${DOWNLOADS_LOCATION}
        target: /downloads
    ports:
      - 8001:8112
    restart: always
    networks:
        proxy:

networks:
  proxy:
     external: true
