services:
  ersatztv:
    container_name: ersatztv
    image: ghcr.io/ersatztv/ersatztv:develop
    restart: always
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    mem_limit: 4G
    memswap_limit: 4G
    dns:
      - 1.1.1.1
      - 9.9.9.9
    security_opt:
      - no-new-privileges=true
    ports:
      - "8003:8409"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ersatztv.rule=Host(`etv.${MY_DOMAIN}`)'
      - 'traefik.http.routers.ersatztv.entrypoints=https'
      - "traefik.http.services.ersatztv.loadbalancer.server.port=8409"
      - "traefik.http.routers.ersatztv.tls=true"
    environment:
      TZ: Asia/Kolkata
      Bugsnag:Enable: false
    volumes:
      - type: tmpfs
        target: /transcode
      - type: bind
        source: ${CONFIG_LOCATION}/Ersatztv
        target: /config
      - type: bind
        source: ${FILLERS_LOCATION}
        target: /mnt/Fillers
        read_only: true
      - type: bind
        source: ${MUSIC_VIDEOS_LOCATION}
        target: /mnt/Music
        read_only: true
      - type: bind
        source: ${MUSIC_LOCATION}
        target: /mnt/Songs
        read_only: true
    networks:
        proxy:

networks:
  proxy:
     external: true
